### ISSUE TITLE
Remove Path2D Typings

### ISSUE THREAD

**Issue by marwahaha** [google/canvas-5-polyfill#12]
TS by default has these typings, and they're conflicting with the typings when I include this library.

https://github.com/Microsoft/TypeScript/blob/v2.2.2/lib/lib.dom.d.ts#L8548

**Comment by marwahaha** [comment]
Seems like they were added recently @jcgregorio 
https://github.com/google/canvas-5-polyfill/pull/8

**Comment by henryptung** [comment]
Agreed; the proper way to deal with this seems to be using ambient typings. All the typings are provided by the `"dom"` TypeScript typings, and including `dom` for other reasons will conflict with this library.

**Comment by marwahaha** [comment]
Just pinging this thread -- I need this removed to get my app working in IE11.

Thanks!

**Comment by zerovox** [comment]
@jcgregorio @ksm2 can we remove the .d.ts file? the conflicts are causing issues for us. Do the standard TS typings not provide everything you need here?

**Comment by zerovox** [comment]
I made a PR - this may break @ksm2 , but it's much easier to _add_ typings upstream to older projects that require them, rather than remove conflicting typings downstream for up-to-date projects that don't need them. The later seems basically impossible, somewhat a flaw in the way typescript works I guess.

**Comment by marwahaha** [comment]
Pinging this thread again @jcgregorio

**Comment by jcgregorio** [comment]
This has been rolled into the 0.1.4 release. Thanks!
